### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by Mythalar** [SpencerMycek/KineticistExpandedElements#2]
Hey there !

First thank you since adding elements is no easy task and aether is a favorite of mine...

I could run some tests and did not spot any big issue (some random typo), but the force composite blast did fire damage so I guess there is a little issue there (divine if no force perhaps?)

I would suggest to add the possibility to use pushing and bowling infusions since, as of now, the main issue is the lack of substance infusion (and we could get rid of earth o' )

I don't know shit about making art/FX but back in Kingmaker CotW mod author added quite some force spells that would be nice (I think there are some nice spells among mythic spells, demon has some force spells), perhaps using Battering blast missile for the force composite basic blast?

But again, thanks a lot for this :)

**Comment by SpencerMycek** [comment]
Hey thank you for testing stuff out. 
I did notice the force blast does “fire”. I tried to model it after the Battering Blast spell, if you could test that to see if they match up, it might show up the same there.

wotr doesn’t appear to have a “force” energy type, instead force is different from energy and physical all together, so definitely still something to fix.

And good call on the substance infusions, they might not be TableTop based, but would add to the element

lastly, for fx, I’ll take a look at CoTW, cause I do want this to all look nice :)


Again, Thank you!

**Comment by Mythalar** [comment]
Yep I'll test it tomorrow if you want.
And will look into force spells that are in-game, or that look like this (Aeon spells perhaps)

And yeah in-game damage that is inevitable or irresistible, such as force, is regularly tagged as divine to bypass resistance (AFAIK that was the case for magic missiles?)

For substance Infusions, if memory serves, telekinetic blast can be used per RAW with pushing and bowling, so the stretch to force composite is not that far !

**Comment by SpencerMycek** [comment]
I was excited enough to test myself after work :)

I actually had a everything in place to use force damage, I just called the wrong function :(
Force blast is now correctly Force Damage, although there is a weird UI bug where Force Kinetic Blade doesn't display damage correctly, so I'll have to look into that.

And I double checked as well, Pushing and Bowling are for Telekinetic blast for TT pathfinder, but not Force.
That upsets me enough to add it to Force, but that might be tomorrow when the fix goes out for those.

Thanks for the call outs :)

**Comment by SpencerMycek** [comment]
Force Blast now does force damage
Force and Telekinetic Blast now both have Pushing and Bowling Infusions (I did not update the infusions descriptions though)

Still working on FX though :)
