### ISSUE TITLE
Suggestion: Many Throw

### ISSUE THREAD

**Issue by RevanStarforge** [SpencerMycek/KineticistExpandedElements#21]
making many throw targeting like an aoe might be more insightful to it's use, like a fireball, because let's look at it's wording

* you can attack up to your kineticist level amount of enemies that are no more then 120 ft away

so range is 120 ft, moving on...

* no two target can be more than 30 ft apart. 

so... among the number of people you're planing to attack, no two of them might be more than 30 ft away... that's a diameter of a circle right there; 30 ft diameter to be exact.

so why not give us a target like fireball does, that has 30 ft in diameter. no two enemies in this circle can be more than 30 ft away from each other anyway, and it would be much more easier to aim

of course, limit the target that'll be effected from the attack to kineticist level, and also exlude allies like selective... And... that's it...

It's more of a quality of life option but still, please keep in mind

**Comment by SpencerMycek** [comment]
I think it's a great Idea, and I'll look into it
But think of it more as a chain, any target cannot be more than 30ft away from the last target

That's at least how I interpret it, it could be similar to a fireball style blast, in which case the mechanics need to change and I would add a targeting circle (if I can)

**Comment by RevanStarforge** [comment]
sure, but it's a not a chain, at least according to the wording, because unlike wording, blast doesn't jump from one target to another, they all orignating from you.


i think the limitation is there because it's a very quick and but also mentally taxing thing, like it's a standart action if not a swift action, that's like either 3 second or 0.5 second of time in real time (since 1 round is 6 second in path/dnd)

in that time, you channel your mind and focus your telekinesis, you shape it into form, you quickly with an eye movement target your intended enemies and salvo multiple 'force punches' or debrees or whatever to these intended targets while trying to be precise as possible. there is factor of the angle you can see in front of you in this blink of an eye situation, you moving your hand from one target to another, ect ect... (like even if you think like a gun, which would be less intensive then literally creating telekinetic powers with your mind/soul i would imagine... you wouldnt have time to shoot two people that too far away from each other in 3 seconds... you couldnt even turn the gun enough if the analogy makes sense?)


at least that's what the intent i'm sensing... chain would work much differently of course and it would be like after the first 120 ft travel, blast would seek a nearby enemy, as taking the latest hit enemy as the new origin point but this time with 30 ft range... which luckly i gues we have already coded chain lightning for that


sorry for long babble, in the end of course do as you think best, but just wanted to convey my thought process and why i think wording fits a circle target system fit perfectly



**AND FINALLY**: i think... The magic missile animation would look much better for this attack. Can you try with magic missile instead of Force Blast (i think that's what you used), it would more feel like a quick salvo attack that you use to attack everywhere at once... and i think it has a beautiful animation...


again, sorry for long ideas

**Comment by RevanStarforge** [comment]
just came up to me... also; do you think you can make it so that many throw's projectile goes off at the same time? instead of one by one... that would be REALLY cool looking
