### ISSUE TITLE
Bug: Expended Elements Feat

### ISSUE THREAD

**Issue by RevanStarforge** [SpencerMycek/KineticistExpandedElements#23]
Once you take the Expended Elements FEAT (not the ability from level up) next expended element feats AND the expended elements Ability that you get from level up goes bananas... it lets you get the elements you already have and hides the ones that you can get but don't have

**Comment by SpencerMycek** [comment]
Not sure what's causing it. Expanded Elements is also part of the Dark Codex mod, so I will do what I can

**Comment by RevanStarforge** [comment]
oh... sorry about that ^^ my bad. also, i bombarded you with alot of issues yesterday, so i also want to say, please take it easy, and thanks for your wonderful mod

**Comment by SpencerMycek** [comment]
No worries, I'm glad there's people out there finding issues to fix, keep sharing anything you find :D

**Comment by SpencerMycek** [comment]
I will say, I tested this, I was able to choose Fire blast for Expanded Elements Feat, and then 2 levels later take Air blast
Not sure what's happening on your end, but if it keeps happening I'll try to fix what I can

**Comment by RevanStarforge** [comment]
what i did was... i just levelled a character from 1 to 20 very quickly and in levelling, i picked aether (not sure if it would even matter) then at level 7 or something i picked water with feat, while i picked aether again with my class's element expension.

then i picked fire, and at that point like void was blacked out, there was 2 water choices available, even though i already had water stuff like that... but i don't know if you can't reproduce it, probably my mods are acting up

**Comment by Truinto** [comment]
Doesn't surprise me that this interaction is funky. There are a couple of conditions I handle differently than the base game. Owlcat has a bit clunky setup with many features requiring the element focus, but there are 3 of each for the different stages (1, 7, and 15).
This is obviously incomparable with the idea of picking bonus elements.

So, here are my requirements in short:
- composite buff (that Owlcat's workaround to grant composite blasts; see cb30a291c75def84090430fbf2b5c05e) needs to grant all composites, except those that have a single parent (e.g. Blueflame and Metal); side note, I replace the whole component in CreateExpandedElement, so if you execute before my patches, it might be futile
- when you grant a BlueprintFeature of an element that could unlock composites, also add the composite buff to it (e.g. anything with more than one parent)
- composite features with a single parent (like Metal) need PrerequisiteFeature on their parent (e.g. Earth)
- most importantly, any wild talents should check for the blast feature, not the element focus or progression

It's probably easier to understand in code. Here https://github.com/Truinto/DarkCodex/blob/a942acc3a788448ebd294647ec3de867cdc796bf/DarkCodex/Kineticist.cs#L313

I have a tree of all features here https://github.com/Truinto/DarkCodex/blob/v1.3.18/DarkCodex/Classes/KineticistTree.cs
If I add your guids, it will make your stuff available as well. Let me know, when you add something new. I will add Void element tomorrow.

If you have any requests or improvements on DarkCodex that would help you, let me know. I am quite impressed you managed to add whole elements so early on.

**Comment by SpencerMycek** [comment]
I love the idea of getting my guids into the kineticist tree you have
In fact, I was half thinking of making a tree of my own so I could merge all my elements into one easy data structure (I think that makes sense, explaining it)
And I definitely intended on switching from adding the focuses to adding the blasts to all of the checks, as it seems it makes it easier, as you've shown in Dark Codex

**Comment by Truinto** [comment]
I updated the tree to include more guids. I didn't have time to add wood yet.

At some point, I could move the tree to CodexLib, if you are interested in using a shared library. It's a bit of WIP, so be wary of methods changing.
