### ISSUE TITLE
Suggestion: Void Healer (Wild Talent)

### ISSUE THREAD

**Issue by RobMatteson** [SpencerMycek/KineticistExpandedElements#26]
`Void Healer
Element void; Type utility (Sp); Level 1; Burn 1
This functions as Kinetic Healer (Pathfinder RPG Occult Adventures 26), except it heals undead (and others healed by negative energy)`

This would make Vampiric Infusion (which you've already implemented for Void) useful for the Dhampir race, Lich mythic path, and Death Domain Clerics.

**Comment by SpencerMycek** [comment]
Oh I didn't even realize kinetic healer didn't work on them, and I was being lazy :D
I'll most likely add this is soon
