### ISSUE TITLE
Bug: Void/Kinetic/Force Blades with Blade Whirlwind

### ISSUE THREAD

**Issue by RevanStarforge** [SpencerMycek/KineticistExpandedElements#29]
blade whirlwind is gray when any of the custom blades are on, and when you click on blade whirlwind anyway, it gives you a weird error... but somehow... not, if you enter in combat..?

**Comment by SpencerMycek** [comment]
I do know the issue here
It looks like I forgot to add the blades to whirlwind
A fix is coming soonish
