### ISSUE TITLE
Suggestion: Void

### ISSUE THREAD

**Issue by RevanStarforge** [SpencerMycek/KineticistExpandedElements#3]
first of all, thank you for your work... i'm an avid kineticist fan, and actualy aether is also my number 1 element too. but second is in tie with air/lightning and void

i'm awere you're working on making aether work good an look good at the same time as of right now. but for future, whatever that future would be far or short, i can't help but ask you to add void second, so i wanted to leave the suggestion here as a reminder

regardless; thanks for the mod

**Comment by SpencerMycek** [comment]
Hey, thank you for the comment.
I would love to add more elements to this, and void is definitely on the list (between it and wood 😄)

not all of the wild talents and infusions are feasible in WoTR, but if you provide a list of the wild talents and infusions that you really want, I’ll do my best to get those in the game, along with any of the others that I can

**Comment by RevanStarforge** [comment]
honestly; i feel aether and void both has alot of RP and tabletop utility potential but very hard to implement in a crpg, but i like to help so i'll take a look into all aether and void talents and try to give feedback as well as how they could be implemented

**Comment by SpencerMycek** [comment]
Even if you just make a list of the talents and infusions you want, that’s all good

I’ll try to add all of them, but some might require some crazy stuff, so I might not immediately do them unless their one of your favorites

I would want to have them all in eventually, but that takes some time

**Comment by RevanStarforge** [comment]
in that case i have no specific preferences or favorites, do them as you can
i mean i would ask singularity but without actual goddamn blackhole animation, i don't know if that thing would be satisfying because it's a very poor wild talent mechanical advantage wise.

a big request would be however; adding omnikinesis. which i gues you can make it work like wandering curse mythic ability, but instead of 1/day, it would be 1 burn per use and could allow you to yoink any blast type or wild talent for 24 hours. it's obviously would be very convoluted though, and owlcat deliberately avoided the kineticist' capstone for a reason, because it suppose to swap an existing one, but that goes into danger zone as far as i understand from code territory. so maybe you could just do as 2 burn instead of 1, but doesn't swap anything and just gives you one extra thing for 24 hour..? not sure...

**Comment by Mythalar** [comment]
The singularity could use the [Supernova Aeon spell FX](https://gfycat.com/yellowhappyjaguar) (which is quite cool, a tad too "lighty" though), but the difficulty would be the changing size I guess.

**Comment by SpencerMycek** [comment]
Hey Everyone! Void is now in the mod, I'm super excited to have gotten this done. It took some time, but everything appears to work. Watch for the new release in a few minutes v2.0.0
