### ISSUE TITLE
Doubt: Elemental Engine

### ISSUE THREAD

**Issue by VitorinoAssuncao** [SpencerMycek/KineticistExpandedElements#32]
First, i need to say thanks, for expanding this class that i simple love. The new elements are all interesthing.

But i'm having some strange behavior:
If a chose any blast like the second in a elemental engine, i just don't obtain the blast per se, just her blade:
![image](https://user-images.githubusercontent.com/47284469/180899143-5d2f0899-fa60-4d06-98e2-6b342466b970.png)
Sorry if this is something intended, but if i chose this element first, work normal.

**Comment by SpencerMycek** [comment]
Did you get the choice between wood/positive when you chose the element on level up?
Just a question to narrow down what the error is

**Comment by VitorinoAssuncao** [comment]
Yes, Spencer, appeared normally, and i chose, Positive Blast.
Just the blast don't appear.

Tried respec the char using ToyBox, and if i select from level 1, Positive Blast, all work correctly, but if a chose in other levels (Second or Third Element), the blast don't appear.
PS: Tried changing for a kineticist, and haves the same behavior.

**Comment by SpencerMycek** [comment]
Very weird, I don't know why that would be the case
I may have to do some testing, but I'll do my best to fix this

**Comment by VitorinoAssuncao** [comment]
For this case, i'm not using the tabletop tweaks, or the darkbook, gonna try with then to see if work.

**Comment by SpencerMycek** [comment]
I have DarkCodex, and it's not working for me either
I modeled Wood and Void after Air, as its another element with a Physical/Energy Choice
But they're not working the same, and you do not get the element.

Until I can figure out why it's not working (beats me), you can add either WoodBlastFeature, PositiveBlastFeature, VoidBlastFeature, or GravityBlastFeature to your character with ToyBox:
Party->Party->Features->Show All   ---> Type "ElementBlastFeature" and hit add

But I'm going to keep trying to understand what the issue may be

**Comment by SpencerMycek** [comment]
2 second after I write that, I found the issue
Keep an eye on the next patch, should fix the issue. Sorry for the delays

**Comment by VitorinoAssuncao** [comment]
You are great Spencer, thanks
