### ISSUE TITLE
Bug: Kinetic Blade not functioning for void elements

### ISSUE THREAD

**Issue by GrocerOfDespair** [SpencerMycek/KineticistExpandedElements#33]
With version 2.5.0 of KEE (this reads as 2.0.2 in UnityModManager) and DarkCodex 1.3.19 kinetic blade is not working for either void or gravity.  The icon is selectable but a blade does not appear in hand and the character uses unarmed strike to attack.  Kinetic whip is grayed out.

**Comment by SpencerMycek** [comment]
I;ve seen that issue too, I'm not sure what causes it, but I don't think it's directly related, but it might be

Try switching to another one of the loadouts and equipping the blade then

**Comment by GrocerOfDespair** [comment]
I did some further testing and it looks like the problem I was having is caused the Elemental Scion archetype added by Dark Codex.  Using a different archetype leads to expected outcomes with the elements you've added.

**Comment by GrocerOfDespair** [comment]
More testing suggests that if you respec with a particular kinetic blade equipped and do not pick that element in the respec the equipment slot the blade was in is both empty and locked.  Changing weapon selection fixes it.  If that makes sense.

**Comment by GrocerOfDespair** [comment]
Which I now realize is what you wrote above.  Apologies for the poor reading comprehension!

**Comment by SpencerMycek** [comment]
No worries, definitely some weirdness going on when mods get involved :D
