### ISSUE TITLE
Bug: Void Kineticist bonus feat not available.

### ISSUE THREAD

**Issue by GrocerOfDespair** [SpencerMycek/KineticistExpandedElements#34]
With version 2.5.0 of KEE (this reads as 2.0.2 in UnityModManager) and DarkCodex 1.3.19 kineticist bonus feats are not available.  They do not show up in the list, not even grayed out.  They did show up with the previous version of both mods installed.  Not sure if this issue belongs here or with Dark Codex.  

Great mod btw, much appreciated.

**Comment by SpencerMycek** [comment]
Ah, I need to investigate, but I think I know the issue

(Wood currently gets two "Bonus Feats" choices, so I'm thinking I was betrayed by copy+paste, and theyre getting mixed up)

**Comment by SpencerMycek** [comment]
Confirmed, that is the exact issue, fix coming when I can get it
