### ISSUE TITLE
Wood element only once

### ISSUE THREAD

**Issue by Rinelw** [SpencerMycek/KineticistExpandedElements#36]
Is it intended behaviour that you can select only one blast from wood element?

**Comment by SpencerMycek** [comment]
Can you provide more detail, expanded element, etc
You should only be able to pick wood or positive level 1, and if you choose wood again at 7 or 15, you should be able to get positive

**Comment by Rinelw** [comment]
I choose positive blast at 7th level and I wasn't able to select wood option at 15th lvl because I already chose a blast from wood category once.

**Comment by Truinto** [comment]
I think that's an issue on my side. I overwrite expanded element. But will be fixed when I update my feature tree.
