### ISSUE TITLE
About translation   

### ISSUE THREAD

**Issue by q892398745** [SpencerMycek/KineticistExpandedElements#37]
Thanks for your mod, I want to translate it into another language, could you please provide an localizationPack.jsoin file?Or do I have to translate and compile in the source code?

**Comment by SpencerMycek** [comment]
Hey, thanks for the offer of help.
I do have things *sort of* set up for stuff like that

I haven’t look into that myself, but if you want to make one, I can figure out how to place it in there
(Once I’m back from vacation :D)

**Comment by q892398745** [comment]
Thank you. I will wait for your update. Have a good time :D

**Comment by SpencerMycek** [comment]
Hey man, I really apologize for the amount of time this took
But localization is available!!
Just add localization for the languages you want into the files in Media/Localization
When you're done, just make a Pull Request for you fork and I can merge and make the update
