### ISSUE TITLE
Kinetic Blade Icon suggestion

### ISSUE THREAD

**Issue by RevanStarforge** [SpencerMycek/KineticistExpandedElements#4]
first thing after glancing and using bunch of stuff from the mod: can you give kinetic blade a blade shaped icon like all other kinetic blades? since specialy becomes hard to see them at first glance because kineticist already has alot of abilities in most circumtance ^^

**Comment by SpencerMycek** [comment]
Absolutely, I’m just lazy and need to steal one of the correct icons. Will hopefully be in the next release

**Comment by SpencerMycek** [comment]
Switched the Icons for Telekinetic Blade/Force Blade to Air/Steam Blade icons.
I'll get around to custom icons eventually
