### ISSUE TITLE
BUG: Wrong text in combat log for Negative Energy Blast

### ISSUE THREAD

**Issue by RobMatteson** [SpencerMycek/KineticistExpandedElements#40]
![20220812_001640](https://user-images.githubusercontent.com/75058538/184284529-8ef35e23-f09e-4f2c-938c-0937508ec71c.jpg)

The attached screenshot is when attacking Negative Energy Blast with the Kinetic Blade Infusion.

The combat log indicates that I attacked with Gravity Blast and used ability Telekinetic Blast. Both are incorrect and should indicate Negative Energy Blast. This might just be a copy and paste issue in the code.

**Comment by SpencerMycek** [comment]
Ah, any easy fix I think. I've done a lot of copy-paste, and this may have caused the issue
