### ISSUE TITLE
BUG: Broken Prerequisite for Vampiric Infusion

### ISSUE THREAD

**Issue by RobMatteson** [SpencerMycek/KineticistExpandedElements#41]
![20220813_201336](https://user-images.githubusercontent.com/75058538/184520424-c73def36-07c1-4787-b8b9-48f9cb835fbb.jpg)

I think the broken prerequisite is Void Healer.

**Comment by SpencerMycek** [comment]
You are absolutely right, I've got a quick change for that coming right up
