### ISSUE TITLE
Possible Bug: Enervating Infusion doesn't stack with Negative Energy Mastery (Lich) 

### ISSUE THREAD

**Issue by RobMatteson** [SpencerMycek/KineticistExpandedElements#42]
Using Enervating Infusion while Negative Energy Mastery is enabled only inflicts a single negative level. Should this inflict two negative levels (one from Enervating Infusion and one from Negative Energy Mastery)?

**Comment by SpencerMycek** [comment]
It definitely should work.
Here's something to test, if you can: Does your blast deal the extra 1d6 negative energy damage?

If so, it may be a weird issue with how both features are interacting while trying to deal negative levels
If not, then it may be a feature issue where the game is not recognizing Negative Energy blast as a kinetic blast

**Comment by SpencerMycek** [comment]
I did a check myself, and I do not believe this is something that can be fixed, but I will keep trying

I do see the bonus damage from NEM (It's slashing but that's what I expected)
But I don't see the negative level

So it is recognizing it as a kinetic blast, but not to add the extra negative level, which I believe is a deeper game-mechanics issue, and I don't know where the cause of that lies

**Comment by SpencerMycek** [comment]
I believe this is an issue with WoTR, and I saw an update to DarkCodex that fixes it
