### ISSUE TITLE
Foe Throw issue, possible mod conflict?

### ISSUE THREAD

**Issue by mjc1677** [SpencerMycek/KineticistExpandedElements#50]
Hello! really like the mod, but it looks like Foe Throw isn't working properly, at least with my current testing setup.
I'm guessing it's either a mod incompatibility or issue with version 1.4 but haven't had luck tracking it down.

steps to reproduce:
1. Have an appropriate leveled Aether Kineticist (tested elemental engine and dark kineticist archtypes as well as base)
2. Have Foe Throw Infusion and available burn
3. use Lift on Medium creature within 30 feet
4. use Throw Target on creature within 30 feet adjacent to lifted creature (tested repeatedly with both adjacent to character)
5. attack animation occurs and log shows "CharacterName uses ability: Throw Target"
6. neither target damaged, no notification of successful or failed fort save, Lift buff/debuff is not removed from lifted target

I tested on some level 1 critters using the new rogue-like DLC about 20 times so I'd like to think they'd fail a fort save once.

Narrowed down my mod list for testing to just tabletop-base, tabletop-core, tabletop-tweaks, and toybox. I don't see anything in tabletop that would conflict so that leaves toybox, but there's no easy way to test without toybox that I know of.
Didn't see anything useful in any of the logs found in the game folder under appdata either unfortunately.

**Comment by SpencerMycek** [comment]
Hmmm, let me try some testing
I didnt have TTT when I wrote that part, so maybe a conflict, or more likely, it slightly changed how something should work for the better, and I need to catch up :D

**Comment by SpencerMycek** [comment]
Ok, so something weird is happening, and I need to do more testing
However, I can't do testing until I get closer to finishing the patch I'm currently working on (I've currently broken everything, and need to fix it)

**Comment by mjc1677** [comment]
No worries, just glad to help find a bug. 
Not to shill for DLC or anything but the new boat one makes a pretty good test shop for bugs since there's not too much unskippable dialogue so it's just straight into dungeon and test the thing.

**Comment by SpencerMycek** [comment]
Definitely a good idea for testing, and probably what I should do (but I have a save in the first dungeon where I can just beat on the water elemental)
