### ISSUE TITLE
BUG: Version 3.0.0 seems to break the Kinetic Fist infusion from Dark Codex

### ISSUE THREAD

**Issue by RobMatteson** [SpencerMycek/KineticistExpandedElements#53]
The Kinetic Fist ability is togglable, but there are no element choices available in the group which means toggling the ability does not apply any damage to unarmed attacks.

**Comment by SpencerMycek** [comment]
Very interesting, let me take a look, although there shouldn't be any issues with element choices

**Comment by SpencerMycek** [comment]
Let me put an issue up on Dark Codex to try and resolve this, not sure what the issue could be

**Comment by SpencerMycek** [comment]
Fixed in v3.0.1
