### ISSUE TITLE
Gravity Infusion doesn't increase dice size

### ISSUE THREAD

**Issue by Xyrmes** [SpencerMycek/KineticistExpandedElements#57]
The gravitic boost infusions don't seem to work, at least as far as I can tell. They're supposed to upgrade to d8s, but the damage dice aren't increasing in size.

**Comment by SpencerMycek** [comment]
Do you have pictures of the combat log? How could I reproduce the issue?

**Comment by Xyrmes** [comment]
> Do you have pictures of the combat log? How could I reproduce the issue?

Please see below. I made a Psychokineticist with Negative/Gravity/Fire, and an Overwhelming Soul with Gravity/Negative/Earth. Both Level 15 during the below pictures.

I added Dark Codex after I made this post. It may have changed something because I didn't get the gravitic boosts automatically by Level 15. I was able to add them in via Toybox. This wasn't an issue before, so I think there may be some compatibility issue between the two mods.

![Negative GBL](https://user-images.githubusercontent.com/31435121/196232198-4f2ffb7c-d8b0-4fd6-9d42-51e11e2cce7c.png)
![Gravity GBG](https://user-images.githubusercontent.com/31435121/196232237-7fece3e0-0bce-4f1f-8a9d-c08c73c3566d.png)
![Negative DGB](https://user-images.githubusercontent.com/31435121/196232253-2dc305ee-602e-4b88-bc42-f0c26e4dcb55.png)
![Fire On](https://user-images.githubusercontent.com/31435121/196232279-535556d9-87cb-4f33-aba3-01e282fbeb13.png)
![Fire DGB](https://user-images.githubusercontent.com/31435121/196232300-c6cf0e
![Lesser On](https://user-images.githubusercontent.com/31435121/196232364-a6a5c1f6-5342-4fb0-a7c4-2295d191aa1b.png)
bc-7b3c-45a6-8542-a4f8ee4d6754.png)
![Greater On](https://user-images.githubusercontent.com/31435121/196232392-7e8f21eb-fad4-4ef9-830b-0ebdddc07b2b.png)
![Both On](https://user-images.githubusercontent.com/31435121/196232417-99e1741f-a6fa-44f5-82a0-7769a66896af.png)

**Comment by SpencerMycek** [comment]
At least for the DarkCodex part, that's a known issue. Having both is a good idea, but does currently stop you from receiving any of the boosts. That is currently being worked on

As for the boosts themselved:
Gravity Blast: Boosted
![image](https://user-images.githubusercontent.com/32203066/196689521-4f53e300-98cd-4b0f-846b-4076fbb336e6.png)
Negative Component of Void Blast: Boosted
![image](https://user-images.githubusercontent.com/32203066/196689835-bea45c52-ebb1-40ff-b88c-97ec4d8cd5e5.png)

And for me, both costs increased correctly. With an additional 2 for simple physical blasts with Gravitic Boost
And an additional 3 for Composite Physical blasts with Greater Gravitic Boost
Same for other physical blasts, and no effect on Fire Blast

Honestly, I'm uncertain what might be causing the behavior you are seeing
