### ISSUE TITLE
Aether boost question

### ISSUE THREAD

**Issue by Mythalar** [SpencerMycek/KineticistExpandedElements#58]
Only a question really : where should I see Aether boost description?
On character creation screen?
Is it granted but simply not showed if using DarkCodex?

Thank you as always for your dedication ☺️

**Comment by SpencerMycek** [comment]
Hey, yeah, theres a note in the "Known Issues" I thought
Dark Codex is currently overwriting the "Composite Buff" which is how a kineticist gains composite blasts, and the boosts. It's much better overall, it just doesn't include the boosts yet. But that is in the works, eventually
