### ISSUE TITLE
Suggestion : AoE form infusion remix

### ISSUE THREAD

**Issue by Mythalar** [SpencerMycek/KineticistExpandedElements#6]
Hey again !

First thanks again for the fixes, no issue so far.

An idea concerning telekinetic (and force, if you want even if not TT true) would be to add the Many Throw form infusion :

_Element(s) [aether]
Type form infusion; Level 8; Burn 4
Prerequisite(s) extended range
Associated Blasts telekinesis
Saving Throw none

You grab a large number of objects and throw them all at once.

You can use your telekinetic blast to make attack roll against a number of targets equal to your kineticist level within 120 feet, but no two targets can be more than 30 feet apart_.

To avoid coding whatsoever, and since you asked some tips to Truinto perhaps you could borrow his Chain infusion and tweak it so it would not lessen damage from one target to the next, be limited to one target/level but be more costly ?
It's not perfect since each attack from Many Throw should emanate from the caster (perhaps would be of influence with pushing infusion?) But the approximation is quite close and that would change from cloud/deadly earth !

**Comment by SpencerMycek** [comment]
Many Foe and Foe throw are definitely something I want to add, however it starts to get very complicated regarding choice a target enemy to throw, on to throw at, and moving units.
And then even more so for Many Throw.

I definitely want to add them, as they are the center piece of the aether blasts, but I want them to be done well, with as little jank as possible, so it may take some time

**Comment by Mythalar** [comment]
Well Many throw is essentially a multi ranged blast with a scaling number of targets, and with the same distance restrictions than chain infusion, hence my proposition of borrowing Truinto production since it's a really nice addition!

**Comment by SpencerMycek** [comment]
Oh man, you have no idea how many years I thought Many Throw was just a bigger Foe Throw, just more targets.

Yeah, definitely something I could add in much sooner, much easier than I thought

**Comment by Mythalar** [comment]
Ah yes I now see what was your point xD

But no that not it ^^

By the way the demon mythic spells [Telekinetic Strike](https://pathfinderwrathoftherighteous.wiki.fextralife.com/Telekinetic+Strike) and [Telekinetic Burst ](https://pathfinderwrathoftherighteous.wiki.fextralife.com/Telekinetic+Burst) are somewhat akin to Foe Throw (but the basic spell damage could be changed to the blast damage).
It's not exactly the same but quite close I think

**Comment by SpencerMycek** [comment]
Hey, I was able to get Foe Throw, Many Throw, and Force Hook working
