### ISSUE TITLE
BUG Report and Translation

### ISSUE THREAD

**Issue by q892398745** [SpencerMycek/KineticistExpandedElements#62]
[l8n.zip](https://github.com/SpencerMycek/KineticistExpandedElements/files/9895310/l8n.zip)
I have translate this mod， Thank you for your reconsitution to separate the text content. However, I tried adding "zhCN" but it didn't work, so I had to change "enGB" directly. Try to correct this if you want, but if you don't, you also can leave it at that, it's up to you.

Then I want to report some bugs.
Greater Toxic is not in the game.
Singularity has two in the game.

**Comment by SpencerMycek** [comment]
Thank you for your work, and thank you for the bug reports, let me take a look at what's going on

**Comment by SpencerMycek** [comment]
From what I can see, Greater Toxic Infusion is in the game (As: Toxic Infusion, Greater)

And I'm not sure what you mean by Singularity having two in game. I did have to make multiple "singularity" features, due to there being 3 ways to get it

**Comment by SpencerMycek** [comment]
Nevermind, I do see the 2 singularity's now
Let me troubleshoot

**Comment by SpencerMycek** [comment]
This will be fixed in the next update
