### ISSUE TITLE
Dark codex developer said you may need to implement a fix (untested)

### ISSUE THREAD

**Issue by nokturnihs** [SpencerMycek/KineticistExpandedElements#64]
Hey man, just a quick heads up but was talking to the dark codex dev and he said he fixed the kinetic fist pop-up but you may need to do a minor update for the lastest patch. I haven't tested it yet but figured you'd want the heads up. Will let you know if there's an issue since he mentioned your mod specifically...

**Comment by nokturnihs** [comment]
So it looks like everything is functioning but the the icons are blank squares in kinetic fist, etc and the infusions spell pouch bubble isn't working with pulling infusion anyway. Everything seems functional though so that's UI cosmetic stuff at this point.

You don't have kinetic blade/whip versions of any of these right?

**Comment by SpencerMycek** [comment]
Hey man, sorry for the super late reply
Updating the mod now/soonish

Not sure why the icons for anything are blank, but that can sometimes happen, and should be fixed soonish(?)
Otherwise no, I don't believe I have blade/whip versions of anything, but I may not understand the question

**Comment by Truinto** [comment]
Can't remember saying this. But the mods were incompatible for a time, because we both had other things to do.
There is still a crash in wood element that my pull request would fix.
