### ISSUE TITLE
Strange Wood Class Skills entry in wild talent picks

### ISSUE THREAD

**Issue by pheonix99** [SpencerMycek/KineticistExpandedElements#68]
There's a pick in the Wild Talents selector for Wood Class Skills that says it adds Knowledge (World) and Lore(Nature) and then is also a feature selector between Trip, Spell Penetration and Precise Shot.

Pretty sure this shouldn't be there.

**Comment by SpencerMycek** [comment]
Good catch - it'll be fixed in the next update
