### ISSUE TITLE
Bug: Metakinesis

### ISSUE THREAD

**Issue by RevanStarforge** [SpencerMycek/KineticistExpandedElements#7]
Quickened metakinesis or any other one doesnt work on the telekinetic and force blasts

**Comment by SpencerMycek** [comment]
Yeah, Ty for putting this here.
There may be one or two or works for, but I think I forgot to put them in for a majority

**Comment by SpencerMycek** [comment]
Metakinesis is all plumbed up, should work with everything. At least it worked for me in my (non-exhaustive) testing
