### ISSUE TITLE
Graphics Artifacts with Wood Blast

### ISSUE THREAD

**Issue by Valdacil** [SpencerMycek/KineticistExpandedElements#73]
I like the line of vines when Wood blast is cast, but those vines tend to stay on the screen for a long time.  After it hits (or misses) the vines should go away but they often don't.

**Comment by SpencerMycek** [comment]
I believe its an issue with the projectile itself, since its part of a spell (Grasping vines? I think), and I'm just stealing the projectile for the blast
If I can find a better projectile for wood, or if it becomes a larger issue, I can change it
