### ISSUE TITLE
Force blast automatically hits (no ranged attack check)

### ISSUE THREAD

**Issue by ghost** [SpencerMycek/KineticistExpandedElements#74]
Hi, 

I have noticed that Force Blast doesn't roll the ranged touch AC check, and always hits. Telekinetic blast works fine. 

![image](https://user-images.githubusercontent.com/122532039/226169851-b9b20c37-c16e-46a8-8f1a-630c91e0d80c.png)

**Comment by SpencerMycek** [comment]
I could be wrong, but maybe things auto hit companions?
If I am wrong, and I probably am, let me check and see why it's not doing an attack roll

**Comment by Mythalar** [comment]
Yes you auto hit companions for what requires attack rolls.
Same thing if you cast a spell that needs touch attack
