### ISSUE TITLE
Very simple fix for the broken Chinese localization

### ISSUE THREAD

**Issue by NosVladimir** [SpencerMycek/KineticistExpandedElements#75]
Currently, the Chinese localization doesn't work because there is a redundant underscore in `zh_CN` in all the json localization files. Simply change all those into `zhCN` will fix the issue and I've tested that locally.

**Comment by SpencerMycek** [comment]
Thank you for the report, let me get on that

**Comment by NosVladimir** [comment]
Welcome back!!

In the mean time I've also started to do some modding on adding [kineticist archetypes](https://github.com/NosVladimir/KineticArchetypes), and I'm super glad that you had made all the elements in a way similar to the base game. That saved me a ton of work for adding cross-mod support. 

Really really good job to you!
