### ISSUE TITLE
Skilled Kineticist - Wood Element

### ISSUE THREAD

**Issue by Ebonmark** [SpencerMycek/KineticistExpandedElements#76]
Hi,

Skilled Kineticist wild talent is not granting the Knowledge (World) skill boost for those with Wood Element primary element. It's also giving a buff icon of a white square.

thanks and love the mod

**Comment by Ebonmark** [comment]
Issue also seems to apply to the Void element. Maybe they are pointing to one of the stock elements like Fire that only increases Nature (Lore)? Aether seems to work correctly (sans the buff icon but thats just cosmetic).

**Comment by SpencerMycek** [comment]
Thank you for the report, not sure what would be causing that, but let me take a look
