### ISSUE TITLE
Element picking order

### ISSUE THREAD

**Issue by Krollbotid** [SpencerMycek/KineticistExpandedElements#77]
I tried to make build of elemental engine with metal blast empowered by gravity. So I need Earth+Earth+Gravity. However, if you pick elements in that exact order gravitic boost doesn't appear.
![image](https://user-images.githubusercontent.com/37172495/232097216-cd368e99-874b-42da-a047-be90c31ba112.png)
![image](https://user-images.githubusercontent.com/37172495/232097864-132f2e06-a217-4320-a3d1-c4d6499b3511.png)
tested in Inevitable Excess.
If gravity is picked as second element, than gravitic boost and metal blast appear normally. In Vanilla game is order of 2nd and 3rd elements doesn't matter. So I guess it's bug
Modlist Bubble Buffs, Custom Npc Portraits, this mod, ToyBox, Visual Adjustments 2.

**Comment by SpencerMycek** [comment]
Hello, sorry it's been so long. I should show up but It's been a while since I've updated things, so there's a chance things aren't working right
Can you try again with the newest update? And let me know if it works?

**Comment by Krollbotid** [comment]
It works. Thanks!
