### ISSUE TITLE
Suggestion (again) : Aether bonus feats and aetheric boost remix

### ISSUE THREAD

**Issue by Mythalar** [SpencerMycek/KineticistExpandedElements#8]
Hello again again... :p 

Some various things that could be of use, or not, depends on what you planned!

If you want to implement Aether bonus feats, same as other elements (that are not TT true but well) I would suggest : 
- Precise Shot
- Spell Penetration
- Greater Spell Penetration
- Trip
- Greater Trip

So that allows one to avoid some pre requisit for Precise shot, same as fire can access faster to Dreadful carnage. Spell penetration can be nice for energy blasts and trip because Aether can be used in place of earth.

Other idea even more homebrew but I personnaly use this in TT since I always felt that Aetheric boost, per RAW, is not of any interest since Empower costs only 1 burn and is nearly always better : 
Only if your first chosen element is Aether : 
- At 7th level, when you have your first composite blast, the kinetecist does +1 dmg/dice on all simple blast
- At 15th level, the kinetecist does +1 dmg/dice on all blasts

As a passive, and since force blast only does simple blast damage, I think it's a nice bonus that : 
1) has no equivalent
2) is not broken since it's only +10 dmg/blast at lvl19
3) it does not add abilities to the interface which is quite loaded ^^

**Comment by SpencerMycek** [comment]
Excellent Ideas, 
I didn't add the bonus feats as I was either too lazy/didn't know what to give Aether, but I will be adding them as soon as I can

And for Aetheric Boost, I can definitely try for either of them, be it an ability or flat buff, but it is something I want to add in some fashion

**Comment by Mythalar** [comment]
Well I thought of the feats just for Aether to be implemented as the ther elements, not that they are so important.

As for Aetheric boost I guess just a passive with a tootip in the Character sheet is enough, same as a passive feat.
If you follow this road it would just be a flat bonus so I guess there is no need for it to actually appear in the abilities tab.

Now I see why nobody tried to add elements earlier ! xD

**Comment by SpencerMycek** [comment]
The most wanted element to add was Aether (as the other base ones are Wood and Void)
And Aether is really, really weird

**Comment by Mythalar** [comment]
Aether is the element that fits the megamind fantasy so that's not a surprise.

Void is quite cool I think, and there are various necromancy spells that are ranged touch (so I guess the respective projectiles are usable) or even AoE spells that would look nice but then again it would involve a lot of work.

**Comment by SpencerMycek** [comment]
So bonus feats are already in, but this fix help with Disintegrating infusion as well

Another thing to note: I might not going ahead with aetheric boost, at least for right now
Mostly because it gets really really weird in there
And I think I had magma blast doing 3 instances of damage for 30, 9, and 49 damage, and I'm not sure where that came from, so I may put this on the backburner, but the ideas are there

**Comment by Mythalar** [comment]
Well aetheric boost is not that important, it'l would be a nice addition since it's paired with any other element but not a game breaking addition...

Will test the feats!
