### ISSUE TITLE
Force Blast no damage

### ISSUE THREAD

**Issue by bittersulahn** [SpencerMycek/KineticistExpandedElements#80]
when acquiring force blast, and using the kinetic blade, the damage is shown to be 0-0

**Comment by SpencerMycek** [comment]
Do you have any other mods enabled, such as Dark Codex or TTT?
I've noticed that issue as well, but I've found that I still deal the damage I should be with Force Blade (and any others)
It appears that it's a UI bug, and I haven't been able to track down why it's like that
