### ISSUE TITLE
Missing asset bundle

### ISSUE THREAD

**Issue by Bredwh** [SpencerMycek/KineticistExpandedElements#81]
[kineticistexpanded.zip](https://github.com/SpencerMycek/KineticistExpandedElements/files/12867329/kineticistexpanded.zip)

I was going through each mod I have one by one to see which was giving errors and warnings by itself at startup (though I also had ModMenu, Mewsifer Console, and Mewsifer Console Menu. And often TT Core and Base since many mods rely on those). This gave a warning about a missing asset bundle.

To reproduce go to ModFinder and have active this mod and only ModMenu, Mewsifer Console, Mewsifer Console Menu, TT Core and TT Base. Then start WotR and wait until get to main start screen. The warnings and error should be in the console by then.

**Comment by SpencerMycek** [comment]
I do not have these issues, it may be fixed with the new (soon) update
