### ISSUE TITLE
Can't edit quickbar

### ISSUE THREAD

**Issue by Wersely** [SpencerMycek/KineticistExpandedElements#82]
When only having this mod, and the requirements for this mod, active the quick bar cannot be edited. Can't add, remove, or move abilities.

**Comment by Truinto** [comment]
Updating CodexLib.dll with this file https://github.com/Truinto/DarkCodex/raw/master/CodexLib/CodexLib.dll will probably fix this.
You can just drop the file in your mod folder, replacing the existing file.

**Comment by SpencerMycek** [comment]
Should either be fixed from the above fix, or with the new (soon) update
