### ISSUE TITLE
[BUG] Since patch - No elements on Level up

### ISSUE THREAD

**Issue by Nickademus84** [SpencerMycek/KineticistExpandedElements#83]
Ever since the new update all the new elements are gone from the level screen.  There are associated errors in the log as well.

`[ExpandedContent] Localization: 3564[KineticistElementsExpanded] Patching BpCache[KineticistElementsExpanded] Patching Patch_AbilityAtWill[KineticistElementsExpanded] Patching Patch_AbilityIsFullRound[KineticistElementsExpanded] Patching Patch_ActionBarConvert[KineticistElementsExpanded] Patching Patch_ActivatableActionBar[KineticistElementsExpanded] Patching Patch_AOEAttackRolls[KineticistElementsExpanded] Patching Patch_ConditionExemption[KineticistElementsExpanded] Patching Patch_ContextStatValue[KineticistElementsExpanded] Patching Patch_ContextValueParams[KineticistElementsExpanded] Patching Patch_DebugReport[KineticistElementsExpanded] Patching Patch_FixAbilityTargets[KineticistElementsExpanded] Patching Patch_SummonWeapon[KineticistElementsExpanded] Patching Patch_GetTargetProjectileFix[KineticistElementsExpanded] Patching Patch_LevelUp[KineticistElementsExpanded] Patching Patch_LocalizationChanged[KineticistElementsExpanded] Patching Patch_MaterialComponent[KineticistElementsExpanded] Patching Patch_MechanicsContextRecalculate[KineticistElementsExpanded] Patching Patch_Prerequisite[KineticistElementsExpanded] Patching Patch_ResourceOverride[KineticistElementsExpanded] Patching Patch_RulebookEventBusPriority[KineticistElementsExpanded] Patching Patch_RuleSpendCharge[KineticistElementsExpanded] Patching Patch_SpellSelectionParametrized[KineticistElementsExpanded] Patching Patch_SuppressError[KineticistElementsExpanded] Patching Patch_TouchPersist[KineticistElementsExpanded] [Exception] HarmonyException - Ambiguous match for HarmonyMethod[(class=Kingmaker.UnitLogic.Commands.UnitUseAbility, methodname=CreateCastCommand, type=Normal, args=undefined)]HarmonyLib.HarmonyException: Ambiguous match for HarmonyMethod[(class=Kingmaker.UnitLogic.Commands.UnitUseAbility, methodname=CreateCastCommand, type=Normal, args=undefined)] ---> System.Reflection.AmbiguousMatchException: Ambiguous match found.  at System.RuntimeType.GetMethodImpl (System.String name, System.Reflection.BindingFlags bindingAttr, System.Reflection.Binder binder, System.Reflection.CallingConventions callConv, System.Type[] types, System.Reflection.ParameterModifier[] modifiers) [0x00059] in <695d1cc93cca45069c528c15c9fdd749>:0   at System.Type.GetMethod (System.String name, System.Reflection.BindingFlags bindingAttr) [0x0000e] in <695d1cc93cca45069c528c15c9fdd749>:0   at HarmonyLib.AccessTools.DeclaredMethod (System.Type type, System.String name, System.Type[] parameters, System.Type[] generics) [0x00028] in <5c856fb19ddb469d99459756a2e14341>:0   at HarmonyLib.PatchTools.GetOriginalMethod (HarmonyLib.HarmonyMethod attr) [0x0004d] in <5c856fb19ddb469d99459756a2e14341>:0    --- End of inner exception stack trace ---  at HarmonyLib.PatchClassProcessor.ReportException (System.Exception exception, System.Reflection.MethodBase original) [0x0010f] in <5c856fb19ddb469d99459756a2e14341>:0   at HarmonyLib.PatchClassProcessor.Patch () [0x00095] in <5c856fb19ddb469d99459756a2e14341>:0   at CodexLib.MasterPatch.PatchSafe (HarmonyLib.Harmony harmony, System.Type patch) [0x0004b] in <6a674e8b9f4d4641a5e3d78cd017c6a7>:0 [KineticistElementsExpanded] Patching Patch_WeaponCategory[KineticistElementsExpanded] Trying to load lanaguage file C:\Program Files (x86)\Steam\steamapps\common\Pathfinder Second Adventure\Mods\KineticistElementsExpanded\enGB.json False True[KineticistElementsExpanded] Loading Kineticist Elements Expanded[KineticistElementsExpanded] Loading Aether.Configure[KineticistElementsExpanded] [Exception] MissingMethodException - void Kingmaker.PubSubSystem.EventBus.RaiseEvent(System.Action`1,bool)System.MissingMethodException: void Kingmaker.PubSubSystem.EventBus.RaiseEvent<!0>(System.Action`1<!!0>,bool)  at KineticistElementsExpanded.KineticLib.Kineticist.TryDarkCodexAddExtraWildTalent (Kingmaker.Blueprints.BlueprintFeatureReference[] feat_ref) [0x0002a] in <ed1e4e80f58e46378c2e2082af458ee9>:0   at KineticistElementsExpanded.ElementAether.Aether.CreateInfusions () [0x00014] in <ed1e4e80f58e46378c2e2082af458ee9>:0   at KineticistElementsExpanded.ElementAether.Aether.Configure () [0x00029] in <ed1e4e80f58e46378c2e2082af458ee9>:0   at KineticistElementsExpanded.StartGameLoader_LoadAllJson.LoadSafe (System.Action action) [0x00041] in <ed1e4e80f58e46378c2e2082af458ee9>:0 [KineticistElementsExpanded] Loading Void.Configure[KineticistElementsExpanded] [Exception] MissingMethodException - void Kingmaker.PubSubSystem.EventBus.RaiseEvent(System.Action`1,bool)System.MissingMethodException: void Kingmaker.PubSubSystem.EventBus.RaiseEvent<!0>(System.Action`1<!!0>,bool)  at KineticistElementsExpanded.KineticLib.Kineticist.TryDarkCodexAddExtraWildTalent (Kingmaker.Blueprints.BlueprintFeatureReference[] feat_ref) [0x0002a] in <ed1e4e80f58e46378c2e2082af458ee9>:0   at KineticistElementsExpanded.ElementVoid.Void.CreateVoidInfusions () [0x00023] in <ed1e4e80f58e46378c2e2082af458ee9>:0   at KineticistElementsExpanded.ElementVoid.Void.Configure () [0x00029] in <ed1e4e80f58e46378c2e2082af458ee9>:0   at KineticistElementsExpanded.StartGameLoader_LoadAllJson.LoadSafe (System.Action action) [0x00041] in <ed1e4e80f58e46378c2e2082af458ee9>:0 [KineticistElementsExpanded] Loading Wood.Configure[KineticistElementsExpanded] [Exception] MissingMethodException - void Kingmaker.PubSubSystem.EventBus.RaiseEvent(System.Action`1,bool)System.MissingMethodException: void Kingmaker.PubSubSystem.EventBus.RaiseEvent<!0>(System.Action`1<!!0>,bool)  at KineticistElementsExpanded.KineticLib.Kineticist.TryDarkCodexAddExtraWildTalent (Kingmaker.Blueprints.BlueprintFeatureReference[] feat_ref) [0x0002a] in <ed1e4e80f58e46378c2e2082af458ee9>:0   at KineticistElementsExpanded.ElementWood.Wood.CreateInfusions () [0x0000f] in <ed1e4e80f58e46378c2e2082af458ee9>:0   at KineticistElementsExpanded.ElementWood.Wood.Configure () [0x0002f] in <ed1e4e80f58e46378c2e2082af458ee9>:0   at KineticistElementsExpanded.StartGameLoader_LoadAllJson.LoadSafe (System.Action action) [0x00041] in <ed1e4e80f58e46378c2e2082af458ee9>:0 [KineticistElementsExpanded] Loading General.Configure[KineticistElementsExpanded] [General][Elemental Engine Additions][KineticistElementsExpanded] [General][EE - Aether][KineticistElementsExpanded] [General][EE - Void][KineticistElementsExpanded] [General][EE - Wood][KineticistElementsExpanded] Finished loading Kineticist Elements Expanded[CodexLib] OnLocaleChanged to enGBThe referenced script on this Behaviour (Game Object '<null>') is missing!The referenced script on this Behaviour (Game Object '<null>') is missing!Parent of RectTransform is being set with parent property. Consider using the SetParent method instead, with the worldPositionStays argument set to false. This will retain local orientation and scale rather than world orientation and scale, which can prevent common UI scaling issues.[ModMenu] Added Mods Menu View[ModMenu] Adding new type prefabs.[ModMenu] Creating image template.[ModMenu] Creating button template.[ModMenu] Creating collapsible header template.[ModMenu] Creating sub header template.[ModMenu] Creating dropdown button template.[ModMenu] Instantiating layout settings.The referenced script on this Behaviour (Game Object '<null>') is missing!Curl error 6: Could not resolve host: siren.owlcat.local[ModMenu] Adding new type prefabs.[ModMenu] Creating image template.[ModMenu] Creating button template.[ModMenu] Creating collapsible header template.[ModMenu] Creating sub header template.[ModMenu] Creating dropdown button template.[Manager] Spawning.[Manager] Checking updates.[ModMenu] Instantiating layout settings.[0ToyBox0] [Warn] per save settings not found, creating new...`

**Comment by Nickademus84** [comment]
The author of Dark Codex has provided a fix that works.

https://github.com/Truinto/DarkCodex/raw/master/CodexLib/CodexLib.dll

**Comment by SpencerMycek** [comment]
Hey, just updated the mod to the current game version. It may not have fixed things, but things should work smoother now
