### ISSUE TITLE
Aether + Bolwing Infusion

### ISSUE THREAD

**Issue by Gyrados15** [SpencerMycek/KineticistExpandedElements#84]
Not sure if this is intentional or not but when choosing Aether / Force and then Bowling infusion, the Infusion doesn't seem to apply

**Comment by SpencerMycek** [comment]
Force blast unfortunately does not work with bowling, telekinetic does, however.
Here's the line from the Tabletop pathfinder rules:
Associated Blasts earth, magma, metal, mud, telekinetic
