### ISSUE TITLE
Unable to use the hotbar/Elements not appearing

### ISSUE THREAD

**Issue by KenjiShiratsuki** [SpencerMycek/KineticistExpandedElements#85]
Hey, all I have installed are Toybox and this mod, and the moment I installed this mod it broke my ability to drag things onto the hotbar, they just float in the air and don't snap on, makes the game basically unplayable for me. Additionally, the elements aren't available so it isn't working anyway. This is a fresh install, tested the ability to move things on the hotbar with vanilla (pass), mod manager only (pass), toybox installed (pass), then this mod in addition to the aforementioned (fail). I don't know where to find the log for errors or anything, but if you can tell me where to find what you need I'll try to get it for you. Please fix this as best you can, I would love to play with Wood and Void again, I was hoping to do a merc group of all Kineticists.

**Comment by SpencerMycek** [comment]
Should be fixed on the newest update (out soon) Probably just an issue since the mod hasn't been updated for a bit
