### ISSUE TITLE
V3.2.4 download being blocked by antivirus

### ISSUE THREAD

**Issue by Xyrmes** [SpencerMycek/KineticistExpandedElements#86]
Just so you know, the mod version 3.2.4 is getting flagged as having a virus when downloaded.

**Comment by SpencerMycek** [comment]
I have been notified of that. I really am not sure what caused it, since I
don’t think anything changed that would cause that.

I work in cybersecurity. So this just becoming a virus from one update to
another kinda stumped me

**Comment by SpencerMycek** [comment]
Not necessarily sure what to do to fix, but I will keep an eye on it
