### ISSUE TITLE
Mod Not Working in this new update

### ISSUE THREAD

**Issue by Ahas162** [SpencerMycek/KineticistExpandedElements#89]
Can't use the mod at all in any kineticist and there archetypes in creation 
![Untitled2](https://github.com/SpencerMycek/KineticistExpandedElements/assets/69490583/9c5e7e84-84b2-4981-bce2-37dc4b6bff3b)
![Untitled](https://github.com/SpencerMycek/KineticistExpandedElements/assets/69490583/8800c61d-c0be-4aed-8ad9-cad36f94ee0c)

**Comment by Ahas162** [comment]
After the new update 2.3.1 isn't appering at all T_T

**Comment by SpencerMycek** [comment]
Working on an update now, which will fix this issue
