### ISSUE TITLE
Bug : blast damage calculation

### ISSUE THREAD

**Issue by Mythalar** [SpencerMycek/KineticistExpandedElements#9]
Some bug, I think : 

As a psychokineticist with 22 WIS (so +6) and level 17 (9th level blasts) : 
- Telekinetic blast should do 9d6 + 9 + 6 (wisdom) but only does 9d6 +6 so I guess it misses the +1 / dice that a physical blast should have
- Force blast, as a simple energy blast, should do 9d6 +3 (half wis) but actually does 9d6 + 7 and I cannot see why...

No burn so no overflow bonus.
Edit : actually the overflow bonus does not apply to telekinetic or force damage, I don't know if it's a bug too.

As a side note, I know that, in TT, Force blast does less damage but is quite irresitible so that's mighty fine, but in WotR with Ascended element every energy resistance can be bypassed so I personnaly would put it on par with Blue Flame to have a direct alternative.

**Comment by SpencerMycek** [comment]
Good catches, 
Currently working on the disintegrating infusion, but once that's done I'll investigate and push out fixes for the damage

And yeah, I wanna take a look into balance tuning for Force Blast, since resistance can be essentially ignored after level 5 or whenever ascended element comes online

**Comment by Mythalar** [comment]
Oh yeah pew pew blast is the best !

That makes me think : is it possible to use disintegrate FX for Force blast, it would be nice (even if no alternative for cloud...)

**Comment by SpencerMycek** [comment]
I'll let you in on a little secret
I saw the Disintegrate projectile was an option, and immediately switched all the force blast variants to use it
So that's coming when I get disintegrate done

**Comment by SpencerMycek** [comment]
And yes, it does look amazing

**Comment by Mythalar** [comment]
Oh yeah pew pew blast is the best 'o'

I reviewed all ranged touch that I can think of and the only ones that, I think, would be good for telekinetic blast are Battering blast (punchy) or Elemental Assessor (lighter)

**Comment by SpencerMycek** [comment]
Got Elemental Overflow hooked up correctly, added the missing 1 damage per die for the physical blasts (spindle was a nightmare, actually crashed WoTR twice), and halved the bonus for Force blasts, but I am still considering boosting to a normal Composite
